### ISSUE TITLE
Load scene in blender/unreal

### ISSUE THREAD

**Issue by eliabntt** [3dlg-hcvc/hssd#1]
Hi, first of all great work, thanks for sharing and release all the data.

I would be interested in using your dataset in my research and try it out. However, I need to load the scene in blender/unreal.
Is that possible?

I'm also curious. How does lighting work in your dataset? do you define light sources/color or is just a plain diffuse lighting condition?

**Comment by mukulkhanna** [comment]
Hello @eliabntt,

> I would be interested in using your dataset in my research and try it out. However, I need to load the scene in blender/unreal.
Is that possible?

Loading the scenes in Blender is indeed possible. You might want to look at the raw, uncompressed HSSD scenes made available [here](https://huggingface.co/datasets/hssd/hssd-models).

> How does lighting work in your dataset? do you define light sources/color or is just a plain diffuse lighting condition?

The lighting depends on the renderer. 

In Habitat, we have a number of default predefined light sources. In Blender, we render using image-based lighting from an environment map.

**Comment by eliabntt** [comment]
Ok thanks.
