### ISSUE TITLE
How to obtain a object list and their position in a scene

### ISSUE THREAD

**Issue by whcpumpkin** [3dlg-hcvc/hssd#10]
Dear authors,
       Thanks for your wonderful dataset!
       When I run the habitat-lab with HSSD dataset, I can not find the function to obtain the loaded object list in the current scene. I want to know how to obtain the object list and their position in the current scene?
       Further more, How to obtain more other metadata in the scene?

**Comment by SamMaoYS** [comment]
Thank you for your interest! I suggest exploring the Habitat lab demo at [habitat-lab-demo](https://aihabitat.org/docs/habitat-lab/habitat-lab-demo.html). This resource provides insights into extracting semantic labels and object locations from the simulator.
