### ISSUE TITLE
How to obtain a fine-grained semantic label using semantic_sensor?

### ISSUE THREAD

**Issue by whcpumpkin** [3dlg-hcvc/hssd#13]
Dear authors,

Thank you for your wonderful dataset.
I found that only 28 categories of objects are used for objectnav and their label are defined at `data/scene_datasets/hssd-hab/semantics/hssd-hab_semantic_lexicon.json`. But in `data/scene_datasets/hssd-hab/semantics/objects.csv`, there are 466 categories are labeled. When I use a semantic_sensor in habitat-lab, I found that only the 28 categories of objects can be labeled EVEN IF I create my own `hssd-hab_semantic_lexicon.json` file with 466 cagegories of objects.

This is my `hssd-hab_semantic_lexicon.json`
![image](https://github.com/3dlg-hcvc/hssd/assets/44776486/6aad174b-df1a-46bc-9b61-a9e78edc57de)

These are the rgb and semantic observations.
![image](https://github.com/3dlg-hcvc/hssd/assets/44776486/a82beb62-bc25-425d-b169-18923162bfe6)
![image](https://github.com/3dlg-hcvc/hssd/assets/44776486/c9084209-5263-4450-a594-c18e318d9929)
it seems that the semantic sensor still use the original `hssd-hab_semantic_lexicon.json` not mine (and I've deleted the original file) so that only part of objects in the rgb image are segmented and their `semantic_id` still use the id in original `hssd-hab_semantic_lexicon.json`.

I would like to know how I can modify the file so that the semantic_ensor detects other objects in the HSSD dataset. 
I checked the official repo for habitat-lab and habitat-sim, but I couldn't find anything about semantic_sensor in the HSSD dataset.

**Comment by SamMaoYS** [comment]
Hi @whcpumpkin,
Thank you for expressing your interest in HSSD. I think to increase the semantic granularity of the HSSD in the Habitat simulator, you also need to update the [object_config](https://huggingface.co/datasets/hssd/hssd-hab/blob/main/objects/0/00386b5179df69aec660a71fb9c65b344857d016.object_config.json), the object config specifies the semantic in the _semantic_id_ attribute. And the _hssd-hab_semantic_lexicon.json_ maps the semantic id to a label with _name_. You can use the objects.csv to map each instance to a new semantic id. 

It is a great idea to enhance the semantics for your tasks. Thank you once again for your interest.

**Comment by whcpumpkin** [comment]
> Hi @whcpumpkin, Thank you for expressing your interest in HSSD. I think to increase the semantic granularity of the HSSD in the Habitat simulator, you also need to update the [object_config](https://huggingface.co/datasets/hssd/hssd-hab/blob/main/objects/0/00386b5179df69aec660a71fb9c65b344857d016.object_config.json), the object config specifies the semantic in the _semantic_id_ attribute. And the _hssd-hab_semantic_lexicon.json_ maps the semantic id to a label with _name_. You can use the objects.csv to map each instance to a new semantic id.
> 
> It is a great idea to enhance the semantics for your tasks. Thank you once again for your interest.

Many thanks for your advice. I got the fine-grained semantic labels successfully!!!!
