### ISSUE TITLE
ProcThor conversion steps

### ISSUE THREAD

**Issue by yushiangw** [3dlg-hcvc/hssd#17]
Hi,
Thanks for open sourcing your work!

I have some modified ProcThor examples (i.e. by adjusting ProcThor's parameters)
Could you provide please some information about how to convert them into Habitat-Lab's format?

**Comment by mukulkhanna** [comment]
Hello @yushiangw, please refer to Appendix section A4 of the HSSD paper for information about the ProcTHOR conversion.

https://arxiv.org/pdf/2306.11290.pdf

**Comment by yushiangw** [comment]
Thank you!
