### ISSUE TITLE
Objectnav Nan distance_to_goal in hssd on Habitat 0.2.5

### ISSUE THREAD

**Issue by Zeying-Gong** [3dlg-hcvc/hssd#19]
I followed the instructions to download dependencies, datasets, and codes. However, the default setting with objectnav_hssd_v0.2.5 will make distance_to_goal to nan (resulting in spl and softspl being nan) from the beginning of training. Upon checking, I found that it seemed to be the problem of the episodes of '107734146_175999971'. I wonder if this is normal for reproduction.

**Comment by mukulkhanna** [comment]
Hello @Zeying-Gong,

This is a common issue that occurs when any aspect of the agent embodiment (e.g. agent radius, height, etc.) are different in both the scenarios. For instance, the episodes were generated using X embodiment, but you could be trying to initialize the agent with Y embodiment. As a result, the navmesh used during episode generation might be different from the navmesh being used in your scenario. Make sure to recompute navmesh (with the same embodiment and with static objects included).

**Comment by Zeying-Gong** [comment]
Thank you for your quick reply, I got it.
