### ISSUE TITLE
Articulated Object Interactions

### ISSUE THREAD

**Issue by dHonerkamp** [3dlg-hcvc/hssd#5]
Hi, great work on this dataset, very exciting.

In its social rearrangement task, the Habitat 3.0 paper shows that it is possible to interact with objects in this dataset for pick&place.

I was wondering if it is also possible to interact with the articulated objects in this dataset? In particular in two ways
- is it possible to open & close the doors (even just with magic simulator actions would be fine)?
- is it possible to open any of the other articulated objects in the scenes, such as drawers and cabinets?

Thanks a lot for your help.

**Comment by mukulkhanna** [comment]
Hello @dHonerkamp, very sorry for the late reply.

At the moment, the dataset does not support articulations. Therefore, it is not possible to do both of the things you mentioned.
