### ISSUE TITLE
What coordinates do we use? The left-hand or the right-hand ?

### ISSUE THREAD

**Issue by yoyoshuang** [3dlg-hcvc/hssd#7]
Hello, thanks for your great work,

I want to know what coordinates do we use for the data? The left-hand or the right-hand ?   And which axes is up? X, Y, Z??

Look forward to your reply !

Thank you !

**Comment by SamMaoYS** [comment]
Hi @yoyoshuang, the coordinates should match the habitat-sim simulator. Please refer to [coordinate-frame-tutorial](https://aihabitat.org/docs/habitat-sim/coordinate-frame-tutorial.html) for more details about the HSSD coordinate frame.
