### ISSUE TITLE
Files do not exist when load hssd in habitat-lab

### ISSUE THREAD

**Issue by whcpumpkin** [3dlg-hcvc/hssd#9]
Dear authors,
        I download the dataset in your huggingface repo, then when I run `python -u -m habitat_baselines.run --config-name=objectnav/hssd-200_ver_clip_hssd-hab.yaml`, it appears many errors shown in the image below.
<img width="848" alt="image" src="https://github.com/3dlg-hcvc/hssd/assets/44776486/90d0eeee-7682-4c8d-8708-09c8b558f2fe">

It seems like some files donot exist in the dataset.
I wonder if I download the full dataset.

**Comment by zonszer** [comment]
Hi @whcpumpkin, I have the same error as yours. Could you share how to fix it? Thanks a lot!

**Comment by whcpumpkin** [comment]
@zonszer Hi, 
Note your dataset path and current working path. If you are in doubt about this you can refer to the dataset path in my repo.
https://github.com/[whcpumpkin/MO-DDN](https://github.com/whcpumpkin/MO-DDN)

**Comment by zonszer** [comment]
> @zonszer Hi, Note your dataset path and current working path. If you are in doubt about this you can refer to the dataset path in my repo. [https://github.com/[whcpumpkin/MO-DDN](https://github.com/whcpumpkin/MO-DDN)](https://github.com/%5Bwhcpumpkin/MO-DDN%5D(https://github.com/whcpumpkin/MO-DDN))

Thanks so much, with my sincere star on your repo!
